version: 2
updates:
  - package-ecosystem: "nuget" # Ecosistema di pacchetti da monitorare
    directory: "/" # Directory del tuo progetto
    schedule:
      interval: "weekly" # Frequenza degli aggiornamenti (puoi cambiare in "daily" o "monthly")
    commit-message:
      prefix: "fix" # Prefisso per il messaggio di commit
    open-pull-requests-limit: 0 # Nessun limite alle PR aperte
