version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/WinHubX/" # Percorso della directory contenente il file .csproj
    schedule:
      interval: "weekly" # Aggiornamenti settimanali
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 0
