version: 2
updates:
  - package-ecosystem: "nuget" # Ecosistema di pacchetti da monitorare
    directory: "/" # Directory del tuo progetto
    schedule:
      interval: "weekly" # Frequenza degli aggiornamenti (puoi cambiare in "daily" o "monthly")
    commit-message:
      prefix: "fix" # Prefisso per il messaggio di commit
    open-pull-requests-limit: 5 # Limite massimo di PR aperte contemporaneamente
    ignore:
      - dependency-name: "Microsoft.NET.Test.Sdk" # Esempio di pacchetto da ignorare
        versions: ["<16.0.0"] # Ignora versioni specifiche
